# Dockerfile
FROM n8nio/n8n:latest
ENV GENERIC_TIMEZONE=Asia/Seoul \
    N8N_BASIC_AUTH_ACTIVE=true \
    N8N_BASIC_AUTH_USER=admin \
    N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
EXPOSE 5678
CMD ["n8n", "start"]
