services:
  - type: docker-compose
    name: n8n-render
    repo: https://github.com/YOUR_USERNAME/n8n-render.git
    branch: main
    dockerComposeFilePath: docker-compose.yml
    envVars:
      - key: N8N_PASSWORD
        sync: false
      - key: POSTGRES_DB_PASSWORD
        sync: false  # PostgreSQL 사용 시
    plan: free
